version = 1

[[annotations]]
path = [
  ".github/workflows/*.yml",
  ".gitignore",
  "*/.SRCINFO",
  "*/.gitignore",
  "*/**.install",
  "*/PKGBUILD",
  "README.md",
  "REUSE.toml",
  "nvchecker.toml",
  "old.json",
  "scripts/**",
  "steamcommunity302/s302",
  "typora-community-plugin/typora-community-plugin.hook",
  "typora-community-plugin/typora-community-plugin.sh",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 lingdianshiren <ldsrwu@foxmail.com>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "LICENSE"
precedence = "aggregate"
SPDX-FileCopyrightText = "2007 Free Software Foundation, Inc. <https://fsf.org/>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "dsh-desktop-linux-bin/LICENSE"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 DeepSeek"
SPDX-License-Identifier = "MIT"
